[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "powershell -ExecutionPolicy Bypass -File ../stm32/flash.ps1"
# Can be replaced with "probe-rs", "stm32flash", "dfu-util" or even with own "flash.sh"

rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[unstable]
build-std = ["core"]
