[workspace]
resolver = "3"
members = [ "crates/midi_parser","crates/synth"]

[profile.dev]
codegen-units = 1
debug = true
lto = false
opt-level = 0

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
