[default.general]
chip = "STM32H755ZITx"
connect_under_reset = false
log_level = "INFO"

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "BlockIfFull", format = "Defmt", show_location = true },
]

[default.reset]
enabled = false
halt_afterwards = false

# [firmware]
# files = [
#     # { path = "target/thumbv7em-none-eabihf/release/dsp", address = "0x08000000" },
#     { path = "target/thumbv7em-none-eabihf/release/interfaces", address = "0x08100000" }
# ]
