[default.general]
chip = "STM32H755ZITx"
connect_under_reset = true

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "BlockIfFull", format = "Defmt", show_location = true },
]

# [default.probe]
# protocol = "Swd"

# defmt = true
