[default.general]
chip = "STM32H755ZITx"
connect_under_reset = true
log_level = "INFO"

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "BlockIfFull", format = "Defmt", show_location = true },
]

[default.reset]
enabled = true
halt_afterwards = true

# [firmware]
# files = [
#     { path = "target/thumbv7em-none-eabihf/release/dsp", address = "0x08000000" },
#     # { path = "../interfaces/target/thumbv7em-none-eabihf/release/interfaces", address = "0x08100000" }
# ]

[gdb.gdb]
enabled = true

[gdb.rtt]
enabled = false

[connect.general]
connect_under_reset = false

[connect.flashing]
enabled = false

[connect.reset]
enabled = false
