set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

set(TOOLCHAIN_PREFIX ${TOOLCHAIN_PATH}/arm-none-eabi)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-gcc.exe)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++.exe)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc.exe)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy.exe CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE    ${TOOLCHAIN_PREFIX}-size.exe    CACHE INTERNAL "size tool")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
